# ################################
# Gofile

# Properties
# appdata: literally, app data

# Funcs
# function createNotification(title, message, type = 'success', duration = 3000)
# function createPopup({ title, content, icon = null, backgroundOpacity = true, showCloseButton = true })
# function createAlert(type, content)

# IDM EF2 File Formats, support CRLF(\r\n) only
# <
# url
# cookie: accountToken=ABCDEFG
# >


# ################################
# AB Download Manager

# ping, expect a pong.
POST http://localhost:15151/ping

# send download task
POST http://localhost:15151/start-headless-download
content-type: application/json

{
  "downloadSource": {
    "link": "url",
    "headers": {
      "cookie": "cookie"
    }
  },
  "name": "file name"
}


# ################################
# Aria2 RPC

# send download task
POST http://localhost:6800/jsonrpc
content-type: application/json

{
  "id": "id",
  "jsonrpc": "2.0",
  "method": "aria2.addUri",
  "params": '[
    "token:your_secret",
    ["url"],
    {
      "header": [
        "Cookie: cookie"
      ],
      "dir": "download directory",
    }
  ]'
}